apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews.bookinfo.svc.cluster.local
  gateways:
    - mesh

  http:
  - name: review-default
    match:
    - sourceLabels:
        bluegreen: blue
    route:
    - destination:
        host: reviews.bookinfo.svc.cluster.local
        port:
          number: 9080
        subset: blue
  - name: review-green
    match:
    - sourceLabels:
        bluegreen: green
    route:
    - destination:
        host: reviews.bookinfo.svc.cluster.local
        port:
          number: 9080
        subset: green

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews.bookinfo.svc.cluster.local
  subsets:
  - name: blue
    labels:
      app: reviews
      bluegreen: blue
  - name: green
    labels:
      app: reviews
      bluegreen: green
